### ISSUE TITLE
add more context to the page

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nur-search#2]
It's just a notion that hit me while visiting the page. If I put myself in the shoes of somebody who doesn't know anything about NUR, it's not clear what this page is about:
![image](https://user-images.githubusercontent.com/3248/84747281-9526c780-afa6-11ea-9b2a-04d52dcaa0e3.png)

my 2 seconds intro paragraph:
> NUR is a registry of Nix User Repositories. We collect and build all of those which are searchable on this page.

**Comment by Mic92** [comment]
Fair enough. `nur-search` definitely needs more love.
The content comes from here:
https://github.com/nix-community/nur-search/blob/master/content/_index.md
