### ISSUE TITLE
NUR side-bar should be expanded by default

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nur-search#4]
It's easy to miss that those exist:

![image](https://user-images.githubusercontent.com/3248/85014853-8b43c680-b156-11ea-980e-f446c3c0daab.png)

**Comment by Mic92** [comment]
I assume this needs to be fixed here: https://github.com/vjeantet/hugo-theme-docdock/tree/8931da249615756ff0d9c9f69a1e0ec8548fc380
The theme is no longer maintained afaik. I don't any other theme that provide similar search features.

**Comment by Mic92** [comment]
It does not seem to be that unmaintained though: https://github.com/vjeantet/hugo-theme-docdock
It was just removed from hugo's website for some reason.

**Comment by Mic92** [comment]
It seems to need to need the `active` css class to be shown by default.

**Comment by Mic92** [comment]
The easiest solution would be to make ./repos the front page because than all repositories are expanded.

**Comment by Mic92** [comment]
Fixed in 31033ce9a0adc6593877aea4b0e505877e38f5b8

will deployed on the next nur update.

**Comment by zimbatm** [comment]
Thanks for looking into it!
