### ISSUE TITLE
Add modules to search

### ISSUE THREAD

**Issue by Alexnortung** [nix-community/nur-search#8]
It should be possible to search for modules and their options like on [Nixos search](https://search.nixos.org/options?)

I would like to help if this is possible, if someone could guide me where to begin :)

**Comment by Mic92** [comment]
No but contributions would welcome. The package is currently done here: https://github.com/nix-community/NUR/blob/master/ci/nur/index.py#L76

**Comment by Mic92** [comment]
and here: https://github.com/nix-community/NUR/blob/master/.github/workflows/update.yml#L40
